version: 1.4.{build}
init:
    - ps: |
            If ($Env:APPVEYOR_REPO_TAG_NAME -match "-"){
              Set-AppveyorBuildVariable -Name "IsPreRelease" -Value True
            }
            Else{
              Set-AppveyorBuildVariable -Name "IsPreRelease" -Value False
            }


before_build:
    - ps: |

            $ver = $Env:APPVEYOR_BUILD_VERSION

            $major = $ver.Split(".")[0]
            $minor = $ver.Split(".")[1]
            $buildnum = $ver.Split(".")[2]
            $buildrev = "0"

            # ###################
            # SET VERSION HEADERS
            # ###################

            $versionInfo = @'
            #pragma once

            #define BUILD_NUMBER	>buildnum
            #define REVISION_NUMBER	>buildrev

            #define PRODUCT_MAJOR_VERSION	>major
            #define PRODUCT_MINOR_VERSION	>minor
            #define PRODUCT_SHORT_VERSION	">major.>minor"
            #define PRODUCT_LONG_VERSION	">major.>minor.>buildnum.>buildrev"

            #define FILE_MAJOR_VERSION	>major
            #define FILE_MINOR_VERSION	>minor
            #define FILE_SHORT_VERSION	">major.>minor"
            #define FILE_LONG_VERSION	">major.>minor.>buildnum.>buildrev"

            '@

            
            $versionInfo = $versionInfo -replace ">buildnum",$buildnum
            $versionInfo = $versionInfo -replace ">buildrev",$buildrev
            $versionInfo = $versionInfo -replace ">major",$major
            $versionInfo = $versionInfo -replace ">minor",$minor
            
            $versionInfo | out-file -FilePath source/VersionInfo.h

            $versionInfo = @'
            #include "StdAfx.h"

            #ifdef _MANAGED

            #pragma managed

            using namespace System::Reflection;
            using namespace System::Runtime::CompilerServices;
            using namespace System::Runtime::InteropServices;

            // General Information about an assembly is controlled through the following
            // set of attributes. Change these attribute values to modify the information
            // associated with an assembly.
            [assembly: AssemblyTitle("BugTrap dynamic link library")];
            [assembly: AssemblyDescription("BugTrap - software error reporting tool")];
            [assembly: AssemblyConfiguration("")];
            [assembly: AssemblyCompany("IntelleSoft")];
            [assembly: AssemblyProduct("BugTrap")];
            [assembly: AssemblyCopyright("Copyright © 2005-2009 IntelleSoft")];
            [assembly: AssemblyTrademark("")];
            [assembly: AssemblyCulture("")];

            // Setting ComVisible to false makes the types in this assembly not visible
            // to COM components.  If you need to access a type in this assembly from
            // COM, set the ComVisible attribute to true on that type.
            [assembly: ComVisible(false)];

            // The following GUID is for the ID of the typelib if this project is exposed to COM
            [assembly: Guid("B3DB7206-529E-4000-B549-CA23E08A37F0")];

            // Version information for an assembly consists of the following four values:
            //
            //      Major Version
            //      Minor Version
            //      Build Number
            //      Revision
            //
            [assembly: AssemblyVersion(">major.>minor.>buildnum.>buildrev")];
            [assembly: AssemblyFileVersion(">major.>minor.>buildnum.>buildrev")];

            using namespace System::Security::Permissions;

            [assembly: SecurityPermission(SecurityAction::RequestMinimum, UnmanagedCode = true)];

            #pragma unmanaged

            #endif // _MANAGED

            '@
            
            $versionInfo = $versionInfo -replace ">buildnum",$buildnum
            $versionInfo = $versionInfo -replace ">buildrev",$buildrev
            $versionInfo = $versionInfo -replace ">major",$major
            $versionInfo = $versionInfo -replace ">minor",$minor
            
            $versionInfo | out-file -FilePath source/AssemblyInfo.cpp

build_script: build.cmd

test: off
#  assemblies:
#    - Unit.Tests.dll

after_build:
    - 7z a BugTrap.zip %APPVEYOR_BUILD_FOLDER%\source\Debug\BugTrapD.dll
    - 7z a BugTrap.zip %APPVEYOR_BUILD_FOLDER%\source\Debug\BugTrapD.lib
    - 7z a BugTrap.zip %APPVEYOR_BUILD_FOLDER%\source\Release\BugTrap.dll
    - 7z a BugTrap.zip %APPVEYOR_BUILD_FOLDER%\source\Release\BugTrap.lib
    - 7z a BugTrap.zip "%APPVEYOR_BUILD_FOLDER%\source\.NET Debug\BugTrapDN.dll"
    - 7z a BugTrap.zip "%APPVEYOR_BUILD_FOLDER%\source\.NET Debug\BugTrapDN.lib"
    - 7z a BugTrap.zip "%APPVEYOR_BUILD_FOLDER%\source\.NET Release\BugTrapN.dll"
    - 7z a BugTrap.zip "%APPVEYOR_BUILD_FOLDER%\source\.NET Release\BugTrapN.lib"
    - 7z a BugTrap.zip %APPVEYOR_BUILD_FOLDER%\source\x64\Debug\BugTrapD-x64.dll
    - 7z a BugTrap.zip %APPVEYOR_BUILD_FOLDER%\source\x64\Debug\BugTrapD-x64.lib
    - 7z a BugTrap.zip %APPVEYOR_BUILD_FOLDER%\source\x64\Release\BugTrap-x64.dll
    - 7z a BugTrap.zip %APPVEYOR_BUILD_FOLDER%\source\x64\Release\BugTrap-x64.lib
    - 7z a BugTrap.zip "%APPVEYOR_BUILD_FOLDER%\source\x64\.NET Debug\BugTrapDN-x64.dll"
    - 7z a BugTrap.zip "%APPVEYOR_BUILD_FOLDER%\source\x64\.NET Debug\BugTrapDN-x64.lib"
    - 7z a BugTrap.zip "%APPVEYOR_BUILD_FOLDER%\source\x64\.NET Release\BugTrapN-x64.dll"
    - 7z a BugTrap.zip "%APPVEYOR_BUILD_FOLDER%\source\x64\.NET Release\BugTrapN-x64.lib"

    - 7z a BugTrap.zip %APPVEYOR_BUILD_FOLDER%\source\BTAtlWindow.h
    - 7z a BugTrap.zip %APPVEYOR_BUILD_FOLDER%\source\BTMfcWindow.h
    - 7z a BugTrap.zip %APPVEYOR_BUILD_FOLDER%\source\BTTrace.h
    - 7z a BugTrap.zip %APPVEYOR_BUILD_FOLDER%\source\BugTrap.h
    
    - 7z a BugTrap.zip %APPVEYOR_BUILD_FOLDER%\pkg\BugTrap.chm
    - 7z a BugTrap.zip %APPVEYOR_BUILD_FOLDER%\pkg\CrashExplorer.exe
    - 7z a BugTrap.zip %APPVEYOR_BUILD_FOLDER%\pkg\dbghelp.dll
    - 7z a BugTrap.zip %APPVEYOR_BUILD_FOLDER%\pkg\ReadMe.txt


artifacts:
    - path: BugTrap.zip
      name: Zip
#    - path: __package\*.nupkg
#      name: NuGet


nuget:
    disable_publish_on_pr: true

deploy:
    - provider: GitHub
      description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
      prerelease: $(IsPreRelease)
      artifact: Zip, NuGet
      auth_token:
          secure: cyivrWQwrZNAb6UCNXlIQlGfVSnKIC6TatUOIP95CQgMeKGnmBSqBgAFv2TsRZhR
      on:
          branch: master
          appveyor_repo_tag: true

    - provider: NuGet
      api_key:
          secure: 1nPS2ttf+N4+FUhd+GZycrL7YzSWQpZjnGOMCb5+pGJXSdx0IFvVF8xhTGna7B9t
      artifact: NuGet
      on:
          branch: master
          appveyor_repo_tag: true