version: 0.{build}
init:
    - ps: |
            If ($Env:APPVEYOR_REPO_TAG_NAME -match "-"){
              Set-AppveyorBuildVariable -Name "IsPreRelease" -Value True
            }
            Else{
              Set-AppveyorBuildVariable -Name "IsPreRelease" -Value False
            }

platform:
    - Win32
    - x64

configuration:
    - Debug
    - Release
    #- Unicode Debug
    #- Unicode Release
    #- .NET Debug
    #- .NET Release

matrix:
    fast_finish: true

build:
    parallel: false
    project: source\BugTrap.sln
    verbosity: detailed

test: off
#  assemblies:
#    - Unit.Tests.dll

after_build:
    - 7z a BugTrap.zip %APPVEYOR_BUILD_FOLDER%\source\Debug\BugTrapD.dll
    - 7z a BugTrap.zip %APPVEYOR_BUILD_FOLDER%\source\Debug\BugTrapD.lib
    - 7z a BugTrap.zip %APPVEYOR_BUILD_FOLDER%\source\Release\BugTrap.dll
    - 7z a BugTrap.zip %APPVEYOR_BUILD_FOLDER%\source\Release\BugTrap.lib

artifacts:
    - path: BugTrap.zip
      name: Zip
#    - path: __package\*.nupkg
#      name: NuGet


nuget:
    disable_publish_on_pr: true

deploy:
    - provider: GitHub
      description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
      prerelease: $(IsPreRelease)
      artifact: Zip, NuGet
      auth_token:
          secure: cyivrWQwrZNAb6UCNXlIQlGfVSnKIC6TatUOIP95CQgMeKGnmBSqBgAFv2TsRZhR
      on:
          branch: master
          appveyor_repo_tag: true

    - provider: NuGet
      api_key:
          secure: 1nPS2ttf+N4+FUhd+GZycrL7YzSWQpZjnGOMCb5+pGJXSdx0IFvVF8xhTGna7B9t
      artifact: NuGet
      on:
          branch: master
          appveyor_repo_tag: true